### ISSUE TITLE
Software error: Invalid number of database users. Expected at least 1.

### ISSUE THREAD

**Issue by Rahulsharma0810** [filerun/docker#10]
```
version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - ./db:/var/lib/mysql

  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    ports:
      - "80:80"
    volumes:
      - /mnt/WD_ELEMENTS_1TB:/var/www/html
      - /root/:/user-files
```

Web IP showing "**Software error: Invalid number of database users. Expected at least 1**."
