### ISSUE TITLE
is it possible for it not to `chown -R www-data` the /user-files?

### ISSUE THREAD

**Issue by sentriz** [filerun/docker#14]
my /user-files is one of my external harddrives. it isn't nice that the entrypoint does this
https://github.com/filerun/docker/blob/master/entrypoint.sh#L9
It breaks other programs that use this harddrive.

Maybe filerun docker could use PGID/PUID env vars like linuxserver?
https://www.linuxserver.io/docs/puid-pgid/

Thank you very much

**Comment by pirate** [comment]
https://github.com/filerun/docker/pull/12

**Comment by filerun** [comment]
Using the latest Docker image, one can now use the following variables:
```
environment:
 APACHE_RUN_USER: user
 APACHE_RUN_USER_ID: 1000
 APACHE_RUN_GROUP: user
 APACHE_RUN_GROUP_ID: 1000
```
