### ISSUE TITLE
Software error: Invalid number of database users. Expected at least one record.

### ISSUE THREAD

**Issue by eleaner** [filerun/docker#15]
I am not able to connect to the docker filerun
everytime getting this error
"Software error: Invalid number of database users. Expected at least one record."

I have no idea what could be the reason

that's my docker-compose.yml

```
version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=filerun
      - MYSQL_USER=filerun
      - MYSQL_PASSWORD=filerun
      - MYSQL_DATABASE=filerun
    volumes:
      - /home/kisiel/filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      - FR_DB_HOST=db
      - FR_DB_PORT=3306
      - FR_DB_NAME=filerun
      - FR_DB_USER=filerun
      - FR_DB_PASS=filerun
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8099:80"
    volumes:
      - /home/kisiel/filerun/html:/var/www/html
      - /home/kisiel/filerun/user-files:/user-files
```
