### ISSUE TITLE
Error when trying to reach the website

### ISSUE THREAD

**Issue by Astorsoft** [filerun/docker#4]
```
Fatal error: Uncaught Error: Call to a member function fetchAll() on null in /var/www/html/system/classes/vendor/FileRun/Utils/DB.php:56 Stack trace: #0 /var/www/html/system/classes/vendor/FileRun/Utils/DP.php(79): FileRun\Utils\DB->GetAll('SELECT * FROM d...') #1 /var/www/html/system/classes/vendor/FileRun/Utils/Settings.php(34): FileRun\Utils\DP->select('*') #2 /var/www/html/system/classes/vendor/FileRun/Utils/Settings.php(11): FileRun\Utils\Settings->getAll() #3 /var/www/html/index.php(144): FileRun\Utils\Settings->__construct() #4 {main} thrown in /var/www/html/system/classes/vendor/FileRun/Utils/DB.php on line 56
```

I just changed the exposed port and volume location:

```
version: '2'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - /opt/filerun/db:/var/lib/mysql

  web:
    depends_on:
      - db
    links:
      - db
    image: afian/filerun
    ports:
      - "8080:80"
    volumes:
      - /opt/filerun/html:/var/www/html
      - /opt/filerun/user-files:/user-files

```
