### ISSUE TITLE
Cannot get filerun working with docker-compose

### ISSUE THREAD

**Issue by g0d-m0nky** [filerun/docker#48]
Hi, I am looking for a bit of help getting filerun up and working on Ubuntu Server.

```
services:
  filerun_db:
    image: mariadb:10.1
    container_name: filerun_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: filerun_db
    volumes:
      - /filerun/db:/var/lib/mysql

  filerun:
    image: filerun/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: filerun_db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun_db
      FR_DB_USER: root
      FR_DB_PASS: root
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_db
    links:
      - db:db
    ports:
      - "8093:80"
    volumes:
      - /mnt/boot/appdata/filerun/html:/var/www/html
      - /mnt/mergerfs:/user-files
```

I am getting the follow messages in my filerun container logs

```
+ id -u www-data
+ '[' '!' -e /var/www/html/index.php ']'
+ echo '[FileRun fresh install]'
+ mysql_host=filerun_db
+ mysql_port=3306
+ /wait-for-it.sh filerun_db:3306 -t 120 -- /import-db.sh
[FileRun fresh install]
wait-for-it.sh: waiting 120 seconds for filerun_db:3306
wait-for-it.sh: filerun_db:3306 is available after 0 seconds
val
2021.12.07
Using existing database!
+ unzip -q /filerun.zip -d /var/www/html/
+ cp /autoconfig.php /var/www/html/system/data/
+ chown -R www-data:www-data /var/www/html
+ chown www-data:www-data /user-files
+ exec /usr/bin/supervisord -c /supervisord.conf
2021-12-23 03:32:34,684 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.35. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.35. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 23 03:32:35.809070 2021] [mpm_prefork:notice] [pid 25] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Thu Dec 23 03:32:35.809608 2021] [core:notice] [pid 25] AH00094: Command line: 'apache2 -D FOREGROUND'
+ id -u www-data
+ '[' '!' -e /var/www/html/index.php ']'
+ exec /usr/bin/supervisord -c /supervisord.conf
2021-12-23 03:41:53,256 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.35. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.35. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 23 03:41:54.468515 2021] [mpm_prefork:notice] [pid 17] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Thu Dec 23 03:41:54.468560 2021] [core:notice] [pid 17] AH00094: Command line: 'apache2 -D FOREGROUND
````

Any help would be much appreciated!
