### ISSUE TITLE
Error message when trying to install

### ISSUE THREAD

**Issue by thimplicity** [filerun/docker#53]
Hi,
when I try to deploy filerun in a docker container, I receive the following error message:

`failed to deploy a stack: Named volume "docker/appdata/filerun/db:/var/lib/mysql:rw" is used in service "db" but no declaration was found in the volumes section. : exit status 1`

I pretty much only copied and pasted the docker instructions from the website and adjusted the volumes to the structure on my server. Any ideas?

**Comment by filerun** [comment]
You have an error in your config. Can help if you can paste the whole thing and not just the error.

**Comment by thimplicity** [comment]
This is my docker compose content:

**Comment by thimplicity** [comment]
Thanks! This is my docker compose file content:

```
version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: qawsed12
      MYSQL_USER: fr_usr
      MYSQL_PASSWORD: qawsed12
      MYSQL_DATABASE: db
    volumes:
      - docker/appdata/filerun/db:/var/lib/mysql

  web:
    image: filerun/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: db
      FR_DB_USER: fr_usr
      FR_DB_PASS: qawsed12
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8082:80"
    volumes:
      - /docker/appdata/filerun/html:/var/www/html
      - /mnt:/user-files
```
