### ISSUE TITLE
Rootless Docker can't write files

### ISSUE THREAD

**Issue by Vandaahl** [filerun/docker#64]
I'm experimenting with rootless docker and Filerun. Needless to say, Filerun by default does not have write permissions to my files. Is there a way to fix this? 

Other project often let you set a UID and GID environment value, which I can set to 0 so the user will match my docker user (which is UID/GID 1000/1000). Here's my docker-compose.yml:

```
services:
  db:
    image: linuxserver/mariadb:arm64v8-10.6.10-r0-ls73
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: username
      MYSQL_PASSWORD: passw
      MYSQL_DATABASE: filerun_database
      PUID: 0
      PGID: 0
      TZ: Europe/London
    volumes:
      - ./db:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  filerun:
    image: filerun/filerun:arm64v8
    container_name: filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun_database
      FR_DB_USER: username
      FR_DB_PASS: passw
      #APACHE_RUN_USER: me
      #APACHE_RUN_USER_ID: 0
      #APACHE_RUN_GROUP: me
      #APACHE_RUN_GROUP_ID: 0
    depends_on:
      - db
    ports:
      - "8044:80"
    volumes:
      - ./html:/var/www/html
      - /home/me/docker:/user-files/docker
      - ./files:/user-files/files
    restart: unless-stopped
```

Setting APACHE_RUN_USER_ID to 0 crashes the Filerun container because Apache can't run as root.
