### ISSUE TITLE
Error while trying to install (docker)

### ISSUE THREAD

**Issue by nnillat** [filerun/docker#66]
I get this error when trying to install via docker, but the yaml syntax looks fine, https://www.yamllint.com/ says it's valid, and it's the default config from the docs.
```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 5, column 44
```

My config file is:
```yml
version: "2"
services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
    volumes:
      - /filerun/db:/var/lib/mysql
  web:
    image: filerun/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 80:80
    volumes:
      - /filerun/html:/var/www/html
      - /filerun/user-files:/user-files
```
